version : '3'
 
services:
  peopleapi:
    image: peopleapi
    ports:
      - 9004:8080
    environment:
      - peopleapicontext=server=peopleapidb;user id=peopleAPI;password=myP@ssw0rd;Database=peopleAPI
    depends_on:
      - peopleapidb
  
  peopleapidb:
    image: peopleapidb
    ports:
      - 1433
