// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using peopleapi.Data;
using System;

namespace peopleapi.Migrations
{
    [DbContext(typeof(peopleAPIContext))]
    [Migration("20180604004424_PeopleAPITable")]
    partial class PeopleAPITable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("peopleapi.Models.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnName("personId");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("CellPhone")
                        .HasColumnName("cellPhone")
                        .HasMaxLength(12)
                        .IsUnicode(false);

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("firstName")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("lastName")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Linkedin")
                        .HasColumnName("linkedin")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("MiddleName")
                        .HasColumnName("middleName")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Twitter")
                        .HasColumnName("twitter")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("WorkPhone")
                        .HasColumnName("workPhone")
                        .HasMaxLength(12)
                        .IsUnicode(false);

                    b.Property<string>("ZipCode")
                        .HasColumnName("zipCode")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasKey("PersonId");

                    b.HasIndex("LastName")
                        .HasName("IX_Person_lastname");

                    b.HasIndex("PersonId")
                        .HasName("IX_Person");

                    b.HasIndex("State")
                        .HasName("IX_Person_state");

                    b.ToTable("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
